# Generated by Django 4.1.1 on 2022-09-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
